// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using YesLojistik.Infrastructure.Data;

#nullable disable

namespace YesLojistik.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260928054718_CustomerStatusEmail")]
    partial class CustomerStatusEmail
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("YesLojistik.Core.Entities.CompanySettings", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("company_name");

                    b.Property<int>("DefaultPaymentTermDays")
                        .HasColumnType("integer")
                        .HasColumnName("default_payment_term_days");

                    b.Property<decimal>("DefaultVatRate")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("default_vat_rate");

                    b.Property<int>("DefaultWithholdingTenths")
                        .HasColumnType("integer")
                        .HasColumnName("default_withholding_tenths");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<bool>("HasSampleData")
                        .HasColumnType("boolean")
                        .HasColumnName("has_sample_data");

                    b.Property<string>("Iban")
                        .HasColumnType("text")
                        .HasColumnName("iban");

                    b.Property<string>("InvoicePrefix")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("invoice_prefix");

                    b.Property<string>("LogoDataUrl")
                        .HasColumnType("text")
                        .HasColumnName("logo_data_url");

                    b.Property<int>("NextInvoiceNumber")
                        .HasColumnType("integer")
                        .HasColumnName("next_invoice_number");

                    b.Property<string>("Phone")
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<DateTime?>("SampleDataClearedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sample_data_cleared_at");

                    b.Property<string>("Slogan")
                        .HasColumnType("text")
                        .HasColumnName("slogan");

                    b.Property<string>("TaxNumber")
                        .HasColumnType("text")
                        .HasColumnName("tax_number");

                    b.Property<string>("TaxOffice")
                        .HasColumnType("text")
                        .HasColumnName("tax_office");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_company_settings");

                    b.ToTable("company_settings", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompanyName = "YES LOJİSTİK",
                            DefaultPaymentTermDays = 30,
                            DefaultVatRate = 20m,
                            DefaultWithholdingTenths = 2,
                            HasSampleData = false,
                            InvoicePrefix = "F",
                            NextInvoiceNumber = 1,
                            Slogan = "Güvenle, Her Yere...",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("YesLojistik.Core.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("address");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("email");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<bool>("NotifyStatusByEmail")
                        .HasColumnType("boolean")
                        .HasColumnName("notify_status_by_email");

                    b.Property<decimal>("OpeningBalance")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("opening_balance");

                    b.Property<DateOnly?>("OpeningBalanceDate")
                        .HasColumnType("date")
                        .HasColumnName("opening_balance_date");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone");

                    b.Property<string>("TaxNumber")
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)")
                        .HasColumnName("tax_number");

                    b.Property<string>("TaxOffice")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tax_office");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_customers");

                    b.HasIndex("Title")
                        .HasDatabaseName("ix_customers_title");

                    b.ToTable("customers", (string)null);
                });

            modelBuilder.Entity("YesLojistik.Core.Entities.Driver", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("LicenseClass")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("license_class");

                    b.Property<DateOnly?>("LicenseExpiry")
                        .HasColumnType("date")
                        .HasColumnName("license_expiry");

                    b.Property<string>("NationalId")
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)")
                        .HasColumnName("national_id");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone");

                    b.Property<DateOnly?>("PsychotechnicExpiry")
                        .HasColumnType("date")
                        .HasColumnName("psychotechnic_expiry");

                    b.Property<DateOnly?>("SrcExpiry")
                        .HasColumnType("date")
                        .HasColumnName("src_expiry");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_drivers");

                    b.ToTable("drivers", (string)null);
                });

            modelBuilder.Entity("YesLojistik.Core.Entities.Expense", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<int?>("DriverId")
                        .HasColumnType("integer")
                        .HasColumnName("driver_id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<decimal?>("Liters")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("liters");

                    b.Property<int?>("Odometer")
                        .HasColumnType("integer")
                        .HasColumnName("odometer");

                    b.Property<int?>("TripId")
                        .HasColumnType("integer")
                        .HasColumnName("trip_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int?>("VehicleId")
                        .HasColumnType("integer")
                        .HasColumnName("vehicle_id");

                    b.HasKey("Id")
                        .HasName("pk_expenses");

                    b.HasIndex("Date")
                        .HasDatabaseName("ix_expenses_date");

                    b.HasIndex("DriverId")
                        .HasDatabaseName("ix_expenses_driver_id");

                    b.HasIndex("TripId")
                        .HasDatabaseName("ix_expenses_trip_id");

                    b.HasIndex("VehicleId")
                        .HasDatabaseName("ix_expenses_vehicle_id");

                    b.ToTable("expenses", (string)null);
                });

            modelBuilder.Entity("YesLojistik.Core.Entities.Invoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer")
                        .HasColumnName("customer_id");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<DateOnly>("DueDate")
                        .HasColumnType("date")
                        .HasColumnName("due_date");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("external_id");

                    b.Property<string>("InvoiceNo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("invoice_no");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("notes");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("subtotal");

                    b.Property<decimal>("Total")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("total");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<decimal>("VatAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("vat_amount");

                    b.Property<decimal>("VatRate")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("vat_rate");

                    b.Property<decimal>("WithholdingAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("withholding_amount");

                    b.Property<int>("WithholdingTenths")
                        .HasColumnType("integer")
                        .HasColumnName("withholding_tenths");

                    b.HasKey("Id")
                        .HasName("pk_invoices");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_invoices_customer_id");

                    b.HasIndex("InvoiceNo")
                        .IsUnique()
                        .HasDatabaseName("ix_invoices_invoice_no");

                    b.ToTable("invoices", (string)null);
                });

            modelBuilder.Entity("YesLojistik.Core.Entities.InvoiceLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("description");

                    b.Property<int>("InvoiceId")
                        .HasColumnType("integer")
                        .HasColumnName("invoice_id");

                    b.Property<int?>("TripId")
                        .HasColumnType("integer")
                        .HasColumnName("trip_id");

                    b.HasKey("Id")
                        .HasName("pk_invoice_lines");

                    b.HasIndex("InvoiceId")
                        .HasDatabaseName("ix_invoice_lines_invoice_id");

                    b.ToTable("invoice_lines", (string)null);
                });

            modelBuilder.Entity("YesLojistik.Core.Entities.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer")
                        .HasColumnName("customer_id");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<int?>("InvoiceId")
                        .HasColumnType("integer")
                        .HasColumnName("invoice_id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("method");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_payments");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_payments_customer_id");

                    b.HasIndex("InvoiceId")
                        .HasDatabaseName("ix_payments_invoice_id");

                    b.ToTable("payments", (string)null);
                });

            modelBuilder.Entity("YesLojistik.Core.Entities.PushToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Platform")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("platform");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("token");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_push_tokens");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("ix_push_tokens_token");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_push_tokens_user_id");

                    b.ToTable("push_tokens", (string)null);
                });

            modelBuilder.Entity("YesLojistik.Core.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("token_hash");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_refresh_tokens_token_hash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_refresh_tokens_user_id");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("YesLojistik.Core.Entities.Trip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer")
                        .HasColumnName("customer_id");

                    b.Property<string>("DeliveryAddress")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("delivery_address");

                    b.Property<DateOnly?>("DeliveryDate")
                        .HasColumnType("date")
                        .HasColumnName("delivery_date");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<int>("DriverId")
                        .HasColumnType("integer")
                        .HasColumnName("driver_id");

                    b.Property<int?>("InvoiceId")
                        .HasColumnType("integer")
                        .HasColumnName("invoice_id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("LoadingAddress")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("loading_address");

                    b.Property<DateOnly>("LoadingDate")
                        .HasColumnType("date")
                        .HasColumnName("loading_date");

                    b.Property<decimal>("SalePrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("sale_price");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<string>("TrackingToken")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("tracking_token");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<decimal>("VehicleCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("vehicle_cost");

                    b.Property<int>("VehicleId")
                        .HasColumnType("integer")
                        .HasColumnName("vehicle_id");

                    b.HasKey("Id")
                        .HasName("pk_trips");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_trips_customer_id");

                    b.HasIndex("DriverId")
                        .HasDatabaseName("ix_trips_driver_id");

                    b.HasIndex("InvoiceId")
                        .HasDatabaseName("ix_trips_invoice_id");

                    b.HasIndex("LoadingDate")
                        .HasDatabaseName("ix_trips_loading_date");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_trips_status");

                    b.HasIndex("TrackingToken")
                        .IsUnique()
                        .HasDatabaseName("ix_trips_tracking_token");

                    b.HasIndex("VehicleId")
                        .HasDatabaseName("ix_trips_vehicle_id");

                    b.ToTable("trips", (string)null);
                });

            modelBuilder.Entity("YesLojistik.Core.Entities.TripAttachment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("content_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("file_name");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("kind");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("note");

                    b.Property<long>("Size")
                        .HasColumnType("bigint")
                        .HasColumnName("size");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("storage_path");

                    b.Property<int>("TripId")
                        .HasColumnType("integer")
                        .HasColumnName("trip_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_trip_attachments");

                    b.HasIndex("TripId")
                        .HasDatabaseName("ix_trip_attachments_trip_id");

                    b.ToTable("trip_attachments", (string)null);
                });

            modelBuilder.Entity("YesLojistik.Core.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<int?>("DriverId")
                        .HasColumnType("integer")
                        .HasColumnName("driver_id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("role");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("DriverId")
                        .HasDatabaseName("ix_users_driver_id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email")
                        .HasFilter("is_deleted = false");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("YesLojistik.Core.Entities.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("brand");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<int?>("DefaultDriverId")
                        .HasColumnType("integer")
                        .HasColumnName("default_driver_id");

                    b.Property<DateOnly?>("InspectionExpiry")
                        .HasColumnType("date")
                        .HasColumnName("inspection_expiry");

                    b.Property<DateOnly?>("InsuranceExpiry")
                        .HasColumnType("date")
                        .HasColumnName("insurance_expiry");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<int>("Km")
                        .HasColumnType("integer")
                        .HasColumnName("km");

                    b.Property<double?>("LastLatitude")
                        .HasColumnType("double precision")
                        .HasColumnName("last_latitude");

                    b.Property<DateTime?>("LastLocationAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_location_at");

                    b.Property<double?>("LastLongitude")
                        .HasColumnType("double precision")
                        .HasColumnName("last_longitude");

                    b.Property<DateOnly?>("LastMaintenanceDate")
                        .HasColumnType("date")
                        .HasColumnName("last_maintenance_date");

                    b.Property<double?>("LastSpeedKmh")
                        .HasColumnType("double precision")
                        .HasColumnName("last_speed_kmh");

                    b.Property<string>("Model")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("model");

                    b.Property<int?>("ModelYear")
                        .HasColumnType("integer")
                        .HasColumnName("model_year");

                    b.Property<DateOnly?>("NextMaintenanceDate")
                        .HasColumnType("date")
                        .HasColumnName("next_maintenance_date");

                    b.Property<string>("Plate")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("plate");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_vehicles");

                    b.HasIndex("DefaultDriverId")
                        .HasDatabaseName("ix_vehicles_default_driver_id");

                    b.HasIndex("Plate")
                        .IsUnique()
                        .HasDatabaseName("ix_vehicles_plate")
                        .HasFilter("is_deleted = false");

                    b.ToTable("vehicles", (string)null);
                });

            modelBuilder.Entity("YesLojistik.Core.Entities.VehicleLocation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<double?>("Accuracy")
                        .HasColumnType("double precision")
                        .HasColumnName("accuracy");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("DriverId")
                        .HasColumnType("integer")
                        .HasColumnName("driver_id");

                    b.Property<double?>("Heading")
                        .HasColumnType("double precision")
                        .HasColumnName("heading");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at");

                    b.Property<double?>("SpeedKmh")
                        .HasColumnType("double precision")
                        .HasColumnName("speed_kmh");

                    b.Property<int?>("TripId")
                        .HasColumnType("integer")
                        .HasColumnName("trip_id");

                    b.Property<int>("VehicleId")
                        .HasColumnType("integer")
                        .HasColumnName("vehicle_id");

                    b.HasKey("Id")
                        .HasName("pk_vehicle_locations");

                    b.HasIndex("RecordedAt")
                        .HasDatabaseName("ix_vehicle_locations_recorded_at");

                    b.HasIndex("TripId", "RecordedAt")
                        .HasDatabaseName("ix_vehicle_locations_trip_id_recorded_at");

                    b.HasIndex("VehicleId", "RecordedAt")
                        .HasDatabaseName("ix_vehicle_locations_vehicle_id_recorded_at");

                    b.ToTable("vehicle_locations", (string)null);
                });

            modelBuilder.Entity("YesLojistik.Core.Entities.Expense", b =>
                {
                    b.HasOne("YesLojistik.Core.Entities.Driver", "Driver")
                        .WithMany()
                        .HasForeignKey("DriverId")
                        .HasConstraintName("fk_expenses_drivers_driver_id");

                    b.HasOne("YesLojistik.Core.Entities.Trip", "Trip")
                        .WithMany("Expenses")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_expenses_trips_trip_id");

                    b.HasOne("YesLojistik.Core.Entities.Vehicle", "Vehicle")
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_expenses_vehicles_vehicle_id");

                    b.Navigation("Driver");

                    b.Navigation("Trip");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("YesLojistik.Core.Entities.Invoice", b =>
                {
                    b.HasOne("YesLojistik.Core.Entities.Customer", "Customer")
                        .WithMany("Invoices")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_invoices_customers_customer_id");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("YesLojistik.Core.Entities.InvoiceLine", b =>
                {
                    b.HasOne("YesLojistik.Core.Entities.Invoice", "Invoice")
                        .WithMany("Lines")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_invoice_lines_invoices_invoice_id");

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("YesLojistik.Core.Entities.Payment", b =>
                {
                    b.HasOne("YesLojistik.Core.Entities.Customer", "Customer")
                        .WithMany("Payments")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_payments_customers_customer_id");

                    b.HasOne("YesLojistik.Core.Entities.Invoice", "Invoice")
                        .WithMany("Payments")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_payments_invoices_invoice_id");

                    b.Navigation("Customer");

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("YesLojistik.Core.Entities.PushToken", b =>
                {
                    b.HasOne("YesLojistik.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_push_tokens_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("YesLojistik.Core.Entities.RefreshToken", b =>
                {
                    b.HasOne("YesLojistik.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_tokens_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("YesLojistik.Core.Entities.Trip", b =>
                {
                    b.HasOne("YesLojistik.Core.Entities.Customer", "Customer")
                        .WithMany("Trips")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_trips_customers_customer_id");

                    b.HasOne("YesLojistik.Core.Entities.Driver", "Driver")
                        .WithMany()
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_trips_drivers_driver_id");

                    b.HasOne("YesLojistik.Core.Entities.Invoice", "Invoice")
                        .WithMany("Trips")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_trips_invoices_invoice_id");

                    b.HasOne("YesLojistik.Core.Entities.Vehicle", "Vehicle")
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_trips_vehicles_vehicle_id");

                    b.Navigation("Customer");

                    b.Navigation("Driver");

                    b.Navigation("Invoice");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("YesLojistik.Core.Entities.TripAttachment", b =>
                {
                    b.HasOne("YesLojistik.Core.Entities.Trip", "Trip")
                        .WithMany("Attachments")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_trip_attachments_trips_trip_id");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("YesLojistik.Core.Entities.User", b =>
                {
                    b.HasOne("YesLojistik.Core.Entities.Driver", "Driver")
                        .WithMany()
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_users_drivers_driver_id");

                    b.Navigation("Driver");
                });

            modelBuilder.Entity("YesLojistik.Core.Entities.Vehicle", b =>
                {
                    b.HasOne("YesLojistik.Core.Entities.Driver", "DefaultDriver")
                        .WithMany()
                        .HasForeignKey("DefaultDriverId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_vehicles_drivers_default_driver_id");

                    b.Navigation("DefaultDriver");
                });

            modelBuilder.Entity("YesLojistik.Core.Entities.Customer", b =>
                {
                    b.Navigation("Invoices");

                    b.Navigation("Payments");

                    b.Navigation("Trips");
                });

            modelBuilder.Entity("YesLojistik.Core.Entities.Invoice", b =>
                {
                    b.Navigation("Lines");

                    b.Navigation("Payments");

                    b.Navigation("Trips");
                });

            modelBuilder.Entity("YesLojistik.Core.Entities.Trip", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("Expenses");
                });
#pragma warning restore 612, 618
        }
    }
}
